name: Check commit message format
on:
  push:
    branches: [ main ]

jobs:
  check-commit-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate commit message format
        run: |
          commit_msg=$(git log --format=%B -n 1 $GITHUB_SHA)
          if ! echo "$commit_msg" | grep -qE "^[A-Z]+-[0-9]+ \| (feat|fix|docs|style|refactor|test|chore) : .*$"; then
            echo "Invalid commit message format. Expected format: JIRA_TICKET | TYPE : MESSAGE"
            exit 1
          fi
